name: nlp_app
description: "A new Flutter project for NLP-APP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_highlight: ^0.7.0
  http: ^1.4.0
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.12

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/images/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
